### ISSUE TITLE
split error

### ISSUE THREAD

**Issue by az4399** [filecoin-project/slate#1019]
[root@iZ1d8r689apel8Z slate]# npm run dev
    
    > slate@1.0.0 dev /root/slate
    > NODE_TLS_REJECT_UNAUTHORIZED=0 node . --unhandled-rejections=strict --max-old-space-size=8192
    
    /root/slate/node_modules/@elastic/elasticsearch/index.js:56
          const cloudUrls = Buffer.from(id.split(':')[1], 'base64').toString().split('$')
                                           ^
    
    TypeError: Cannot read property 'split' of undefined
        at new Client (/root/slate/node_modules/@elastic/elasticsearch/index.js:56:40)
        at Object.<anonymous> (/root/slate/node_common/managers/search/search-client.js:5:22)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Module._compile (/root/slate/node_modules/pirates/lib/index.js:99:24)
        at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Object.newLoader [as .js] (/root/slate/node_modules/pirates/lib/index.js:104:7)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! slate@1.0.0 dev: `NODE_TLS_REJECT_UNAUTHORIZED=0 node . --unhandled-rejections=strict --max-old-space-size=8192`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the slate@1.0.0 dev script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2021-11-29T14_55_06_591Z-debug.log### Error when trying to start，I didn't set `.env`

┆Issue is synchronized with this [Notion page](https://www.notion.so/split-error-b14c343528ca4c6f96f4189673664017) by [Unito](https://www.unito.io)

**Comment by az4399** [comment]
Error when trying to start，but I didn't set `.env`
