### ISSUE TITLE
Textile Buckets: Issue with Stream Upload for larger file sizes, even when HighWaterMarked.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#155]
# Introduction

I'd like to use Readable Streams (or any stream) to send data to the Textile `pushPath` method.

* I don't want to have a temporary local file I add and remove.
* Helps me avoid bad failure states.

There are 3 strategies in this issue, the first two are designed to work with Amazon S3, so I would expect they work with Textile's Buckets too.

## Current implementations

Broken for large files (over 5mb) stream implementation: 
https://github.com/filecoin-project/slate/blob/main/node_common/upload.js

FS.createReadStream implementation **(In use now / works)**: 
https://github.com/filecoin-project/slate/blob/main/node_common/upload-fs.js

## First stream implementation attempt.

This is the first implementation attempt at getting streams to work with the `PassThrough` stream constructor.

```js

import * as LibraryManager from "~/node_common/managers/library";
import * as Utilities from "~/node_common/utilities";

import FORM from "formidable";

import { PassThrough } from "stream";

export const formMultipart = (req, res, { user }) =>
  new Promise(async (resolve, reject) => {
    const f = new FORM.IncomingForm();
    const p = new PassThrough({ highWaterMark: 1024 * 1024 * 3 });
    const file = {};

    const { buckets, bucketKey } = await Utilities.getBucketAPIFromUserToken(user.data.tokens.api);

    f.keepExtensions = true;

    f.onPart = (part) => {
      if (!part.filename) {
        form.handlePart(part);
        return;
      }

      file.name = part.filename;
      file.type = part.mime;

      part.on("data", function (buffer) {
        p.write(buffer);
      });

      part.on("end", function (data) {
        p.end();
      });
    };

    f.on("progress", (bytesReceived, bytesExpected) => {
      // console.log({ bytesReceived, bytesExpected });
    });

    f.parse(req, async (e) => {
      if (e) {
        return reject({});
      }

      if (!file && !file.name) {
        return reject({});
      }

      // NOTE(jim): Creates a Slate compatable Data object.
      const data = LibraryManager.createLocalDataIncomplete(file);

      let push;
      try {
        push = await buckets.pushPath(bucketKey, data.name, p);
      } catch (e) {
        return reject({});
      }

      return resolve({});
    });
  });
```

## Results

* When I upload **5mb** files, everything works as expected.
* When I upload **25mb** files, everything works as expected.
* When I upload **70mb+** files, the stream is constructed (PassThrough) as expected, **but I get the following error from Textile**

```js
{
  decorator: 'SERVER_BUCKETS_VERIFY_ISSUE',
  error: true,
  message: Error: Auth expired. Consider calling withKeyInfo or withAPISig to refresh.
      at Object.<anonymous> (/Users/whiteharbor/Development/slate/node_modules/@textile/security/src/index.ts:146:32)
      at Module._compile (internal/modules/cjs/loader.js:1200:30)
      at Module._compile (/Users/whiteharbor/Development/slate/node_modules/pirates/lib/index.js:99:24)
      at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
      at Object.newLoader [as .js] (/Users/whiteharbor/Development/slate/node_modules/pirates/lib/index.js:104:7)
      at Module.load (internal/modules/cjs/loader.js:1049:32)
      at Function.Module._load (internal/modules/cjs/loader.js:937:14)
      at Module.require (internal/modules/cjs/loader.js:1089:19)
      at require (internal/modules/cjs/helpers.js:73:18)
      at Object.<anonymous> (/Users/whiteharbor/Development/slate/node_modules/@textile/context/src/index.ts:2:1)
}
```

If you're curious about the Stream, whether or not the node constructor is getting the correct `_writeableState` or `_readableState` have the correct HighWaterMark value, I have checked and it seems correct:

```js
_writableState: WritableState {
    objectMode: false,
    highWaterMark: 3145728,
    finalCalled: false,
    needDrain: false,
    ending: true,
    ended: true,
    finished: false,
    destroyed: false,
    decodeStrings: true,
    defaultEncoding: 'utf8',
    length: 791699,
    writing: true,
    corked: 0,
    sync: false,
    bufferProcessing: false,
}
```

### Thank you Textile!

**Comment by jimmylee** [comment]
I'm going to try the `Transform` strategy next!

**Comment by jimmylee** [comment]
## The original solution that still works:

```js
import * as Constants from "~/node_common/constants";
import * as LibraryManager from "~/node_common/managers/library";
import * as Utilities from "~/node_common/utilities";

import FS from "fs-extra";
import FORM from "formidable";

// TODO(jim): Ideally we never keep the file locally.
export const formMultipart = (req, res, { user }) =>
  new Promise((resolve, reject) => {
    const f = new FORM.IncomingForm();
    f.uploadDir = Constants.FILE_STORAGE_URL;
    f.keepExtensions = true;
    f.parse(req, async (e, fields, files) => {
      if (e) {
        return reject({
          decorator: "SERVER_UPLOAD_PARSE_FAILURE",
          error: true,
          message: e,
        });
      }

      if (!files.data) {
        return reject({
          decorator: "SERVER_UPLOAD_ERROR_CHECK_FORM_TYPE",
          error: true,
          message: files,
        });
      }

      const path = files.data._writeStream.path;
      const localPath = `./${path}`;
      const data = LibraryManager.createLocalDataIncomplete(files.data);

      const { buckets, bucketKey, bucketName } = await Utilities.getBucketAPIFromUserToken(user.data.tokens.api);

      let readFile;
      let push;
      try {
        readFile = FS.createReadStream(path, {
          highWaterMark: 1024 * 1024 * 3,
        });

        console.log(readFile);

        push = await buckets.pushPath(bucketKey, data.name, readFile);
      } catch (e) {
        await FS.unlinkSync(localPath);

        return reject({
          decorator: "SERVER_BUCKETS_PUSH_ISSUE",
          error: true,
          message: e,
        });
      }
      // NOTE(jim): Remove the file when you're done with it.
      await FS.unlinkSync(localPath);

      return resolve({ data, ipfs: push.path.path });
    });
  });

```

If you're going the traditional route of writing a file to disk, you end up with a constructor that ends up looking like this:

```js

ReadStream {
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 3145728,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: false,
    destroyed: false,
    errored: false,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: null
  },
  _events: [Object: null prototype] { end: [Function (anonymous)] },
  _eventsCount: 1,
  _maxListeners: undefined,
  path: 'public/static/files/upload_eb623e4ba2126c921a6e8afdeddbb474.pdf',
  fd: null,
  flags: 'r',
  mode: 438,
  start: undefined,
  end: Infinity,
  autoClose: true,
  pos: undefined,
  bytesRead: 0,
  closed: false,
  [Symbol(kFs)]: {
    appendFile: [Function: appendFile],
    appendFileSync: [Function: appendFileSync],
    access: [Function: access],
    accessSync: [Function: accessSync],
    chown: [Function: chown],
    chownSync: [Function: chownSync],
    chmod: [Function: chmod],
    chmodSync: [Function: chmodSync],
    close: [Function: close],
    closeSync: [Function: closeSync],
    copyFile: [Function: copyFile],
    copyFileSync: [Function: copyFileSync],
    createReadStream: [Function: createReadStream],
    createWriteStream: [Function: createWriteStream],
    exists: [Function: exists],
    existsSync: [Function: existsSync],
    fchown: [Function: fchown],
    fchownSync: [Function: fchownSync],
    fchmod: [Function: fchmod],
    fchmodSync: [Function: fchmodSync],
    fdatasync: [Function: fdatasync],
    fdatasyncSync: [Function: fdatasyncSync],
    fstat: [Function: fstat],
    fstatSync: [Function: fstatSync],
    fsync: [Function: fsync],
    fsyncSync: [Function: fsyncSync],
    ftruncate: [Function: ftruncate],
    ftruncateSync: [Function: ftruncateSync],
    futimes: [Function: futimes],
    futimesSync: [Function: futimesSync],
    lchown: [Function: lchown],
    lchownSync: [Function: lchownSync],
    lchmod: [Function: lchmod],
    lchmodSync: [Function: lchmodSync],
    link: [Function: link],
    linkSync: [Function: linkSync],
    lstat: [Function: lstat],
    lstatSync: [Function: lstatSync],
    mkdir: [Function: mkdir],
    mkdirSync: [Function: mkdirSync],
    mkdtemp: [Function: mkdtemp],
    mkdtempSync: [Function: mkdtempSync],
    open: [Function: open],
    openSync: [Function: openSync],
    opendir: [Function: opendir],
    opendirSync: [Function: opendirSync],
    readdir: [Function: readdir],
    readdirSync: [Function: readdirSync],
    read: [Function: read],
    readSync: [Function: readSync],
    readv: [Function: readv],
    readvSync: [Function: readvSync],
    readFile: [Function: readFile],
    readFileSync: [Function: readFileSync],
    readlink: [Function: readlink],
    readlinkSync: [Function: readlinkSync],
    realpath: [Function: realpath] { native: [Function (anonymous)] },
    realpathSync: [Function: realpathSync] { native: [Function (anonymous)] },
    rename: [Function: rename],
    renameSync: [Function: renameSync],
    rmdir: [Function: rmdir],
    rmdirSync: [Function: rmdirSync],
    stat: [Function: stat],
    statSync: [Function: statSync],
    symlink: [Function: symlink],
    symlinkSync: [Function: symlinkSync],
    truncate: [Function: truncate],
    truncateSync: [Function: truncateSync],
    unwatchFile: [Function: unwatchFile],
    unlink: [Function: unlink],
    unlinkSync: [Function: unlinkSync],
    utimes: [Function: utimes],
    utimesSync: [Function: utimesSync],
    watch: [Function: watch],
    watchFile: [Function: watchFile],
    writeFile: [Function: writeFile],
    writeFileSync: [Function: writeFileSync],
    write: [Function: write],
    writeSync: [Function: writeSync],
    writev: [Function: writev],
    writevSync: [Function: writevSync],
    Dir: [Function: Dir],
    Dirent: [Function: Dirent],
    Stats: [Function: Stats],
    ReadStream: [Getter/Setter],
    WriteStream: [Getter/Setter],
    FileReadStream: [Getter/Setter],
    FileWriteStream: [Getter/Setter],
    _toUnixTimestamp: [Function: toUnixTimestamp],
    F_OK: 0,
    R_OK: 4,
    W_OK: 2,
    X_OK: 1,
    constants: [Object: null prototype] {
      UV_FS_SYMLINK_DIR: 1,
      UV_FS_SYMLINK_JUNCTION: 2,
      O_RDONLY: 0,
      O_WRONLY: 1,
      O_RDWR: 2,
      UV_DIRENT_UNKNOWN: 0,
      UV_DIRENT_FILE: 1,
      UV_DIRENT_DIR: 2,
      UV_DIRENT_LINK: 3,
      UV_DIRENT_FIFO: 4,
      UV_DIRENT_SOCKET: 5,
      UV_DIRENT_CHAR: 6,
      UV_DIRENT_BLOCK: 7,
      S_IFMT: 61440,
      S_IFREG: 32768,
      S_IFDIR: 16384,
      S_IFCHR: 8192,
      S_IFBLK: 24576,
      S_IFIFO: 4096,
      S_IFLNK: 40960,
      S_IFSOCK: 49152,
      O_CREAT: 512,
      O_EXCL: 2048,
      UV_FS_O_FILEMAP: 0,
      O_NOCTTY: 131072,
      O_TRUNC: 1024,
      O_APPEND: 8,
      O_DIRECTORY: 1048576,
      O_NOFOLLOW: 256,
      O_SYNC: 128,
      O_DSYNC: 4194304,
      O_SYMLINK: 2097152,
      O_NONBLOCK: 4,
      S_IRWXU: 448,
      S_IRUSR: 256,
      S_IWUSR: 128,
      S_IXUSR: 64,
      S_IRWXG: 56,
      S_IRGRP: 32,
      S_IWGRP: 16,
      S_IXGRP: 8,
      S_IRWXO: 7,
      S_IROTH: 4,
      S_IWOTH: 2,
      S_IXOTH: 1,
      F_OK: 0,
      R_OK: 4,
      W_OK: 2,
      X_OK: 1,
      UV_FS_COPYFILE_EXCL: 1,
      COPYFILE_EXCL: 1,
      UV_FS_COPYFILE_FICLONE: 2,
      COPYFILE_FICLONE: 2,
      UV_FS_COPYFILE_FICLONE_FORCE: 4,
      COPYFILE_FICLONE_FORCE: 4
    },
    promises: [Getter],
    appendFileAsync: [Function: ret],
    appendFileSyncAsync: [Function: ret],
    accessAsync: [Function: ret],
    accessSyncAsync: [Function: ret],
    chownAsync: [Function: ret],
    chownSyncAsync: [Function: ret],
    chmodAsync: [Function: ret],
    chmodSyncAsync: [Function: ret],
    closeAsync: [Function: ret],
    closeSyncAsync: [Function: ret],
    copyFileAsync: [Function: ret],
    copyFileSyncAsync: [Function: ret],
    createReadStreamAsync: [Function: ret],
    createWriteStreamAsync: [Function: ret],
    existsAsync: [Function: ret],
    existsSyncAsync: [Function: ret],
    fchownAsync: [Function: ret],
    fchownSyncAsync: [Function: ret],
    fchmodAsync: [Function: ret],
    fchmodSyncAsync: [Function: ret],
    fdatasyncAsync: [Function: ret],
    fdatasyncSyncAsync: [Function: ret],
    fstatAsync: [Function: ret],
    fstatSyncAsync: [Function: ret],
    fsyncAsync: [Function: ret],
    fsyncSyncAsync: [Function: ret],
    ftruncateAsync: [Function: ret],
    ftruncateSyncAsync: [Function: ret],
    futimesAsync: [Function: ret],
    futimesSyncAsync: [Function: ret],
    lchownAsync: [Function: ret],
    lchownSyncAsync: [Function: ret],
    lchmodAsync: [Function: ret],
    lchmodSyncAsync: [Function: ret],
    linkAsync: [Function: ret],
    linkSyncAsync: [Function: ret],
    lstatAsync: [Function: ret],
    lstatSyncAsync: [Function: ret],
    mkdirAsync: [Function: ret],
    mkdirSyncAsync: [Function: ret],
    mkdtempAsync: [Function: ret],
    mkdtempSyncAsync: [Function: ret],
    openAsync: [Function: ret],
    openSyncAsync: [Function: ret],
    opendirAsync: [Function: ret],
    opendirSyncAsync: [Function: ret],
    readdirAsync: [Function: ret],
    readdirSyncAsync: [Function: ret],
    readAsync: [Function: ret],
    readSyncAsync: [Function: ret],
    readvAsync: [Function: ret],
    readvSyncAsync: [Function: ret],
    readFileAsync: [Function: ret],
    readFileSyncAsync: [Function: ret],
    readlinkAsync: [Function: ret],
    readlinkSyncAsync: [Function: ret],
    realpathAsync: [Function: ret],
    realpathSyncAsync: [Function: ret],
    renameAsync: [Function: ret],
    renameSyncAsync: [Function: ret],
    rmdirAsync: [Function: ret],
    rmdirSyncAsync: [Function: ret],
    statAsync: [Function: ret],
    statSyncAsync: [Function: ret],
    symlinkAsync: [Function: ret],
    symlinkSyncAsync: [Function: ret],
    truncateAsync: [Function: ret],
    truncateSyncAsync: [Function: ret],
    unwatchFileAsync: [Function: ret],
    unlinkAsync: [Function: ret],
    unlinkSyncAsync: [Function: ret],
    utimesAsync: [Function: ret],
    utimesSyncAsync: [Function: ret],
    watchAsync: [Function: ret],
    watchFileAsync: [Function: ret],
    writeFileAsync: [Function: ret],
    writeFileSyncAsync: [Function: ret],
    writeAsync: [Function: ret],
    writeSyncAsync: [Function: ret],
    writevAsync: [Function: ret],
    writevSyncAsync: [Function: ret],
    DirAsync: [Function: ret],
    DirentAsync: [Function: ret],
    StatsAsync: [Function: ret]
  },
  [Symbol(kCapture)]: false,
  [Symbol(kIsPerformingIO)]: false
}
```

* The point I want to make here is that neither Stream solutions I have tried produce the same constructor. Maybe it is expected that the stream have some of these constructor arguments?

**Comment by andrewxhill** [comment]
Hmm... my first thought is that the first error `SERVER_BUCKETS_VERIFY_ISSUE` appears to come from a very long (time-wise) request taking so long that your api session expires first. 


in the second example, you are running,


```
export const formMultipart = (req, res, { user }) =>
  new Promise(async (resolve, reject) => {
    let form = new B({
      headers: req.headers,
      highWaterMark: HIGH_WATER_MARK,
    });

    let fields = [];
    let buffer = null;
    let target = null;

    form.on("file", function (fieldname, file, filename, encoding, mime) {
      file.on("data", (data) => {
```

At which point you process the stream, why not pass the stream directly to the uploader.

```
export const formMultipart = (req, res, { user }) =>
  new Promise(async (resolve, reject) => {
    let form = new B({
      headers: req.headers,
      highWaterMark: HIGH_WATER_MARK,
    });

    let fields = [];
    let buffer = null;
    let target = null;

    try {
        push = await buckets.pushPath(bucketKey, filename, file);
```

I'm less familiar with the `formidable` method, but it appears to be doing similar, processing the entire stream and only then uploading it. not sure this will entirely fix the timeout.

**Comment by jimmylee** [comment]
@andrewxhill super appreciate you jumping in, thanks.

* Last night I was using a connection that was really slow so that may have been causing problems. However this might reveal another issue where a slow connection should still be able to upload a file.
* I'm going to try solutions where I can pass the part over to the same pushPath, is there a link to a file where I can see pushPaths implementation more clearly?

**Comment by jimmylee** [comment]
Solved it here: https://github.com/filecoin-project/slate/blob/main/node_common/upload.js

**Comment by andrewxhill** [comment]
sweet. just for closing the loop. implementation can be seen here,

https://github.com/textileio/js-hub/blob/master/packages/buckets/src/api/index.ts#L308

and

https://github.com/textileio/js-hub/blob/master/packages/buckets/src/api/normalize.ts
